import { Room, Booking, Transaction } from './types';

export const rooms: Room[] = [
  { id: '1', number: '101', type: 'Deluxe', status: 'Occupied', floor: 1 },
  { id: '2', number: '102', type: 'Standard', status: 'Maintenance', floor: 1 },
  { id: '3', number: '103', type: 'Suite', status: 'Occupied', floor: 1 },
  { id: '4', number: '104', type: 'Deluxe', status: 'Cleaning', floor: 1 },
  { id: '5', number: '108', type: 'Standard', status: 'Available', floor: 1 },
  { id: '6', number: '112', type: 'Standard', status: 'Available', floor: 1 },
  { id: '7', number: '201', type: 'Penthouse', status: 'Occupied', floor: 2 },
  { id: '8', number: '215', type: 'Suite', status: 'Occupied', floor: 2 },
  { id: '9', number: '304', type: 'Standard', status: 'Cleaning', floor: 3 },
  { id: '10', number: '312', type: 'Deluxe', status: 'Checked-out' as any, floor: 3 }, // Special status for demo
  { id: '11', number: '402', type: 'Deluxe', status: 'Available', floor: 4 },
  { id: '12', number: '504', type: 'Penthouse', status: 'Available', floor: 5 },
];

export const bookings: Booking[] = [
  {
    id: 'BK-99021',
    guestName: 'Eleanor Shellstrop',
    guestEmail: 'eleanor@thegoodplace.com',
    roomId: '11',
    checkIn: '2023-10-14',
    checkOut: '2023-10-18',
    status: 'Confirmed',
    totalAmount: 1250,
    paidAmount: 1250,
    nights: 4,
  },
  {
    id: 'BK-99025',
    guestName: 'Chidi Anagonye',
    guestEmail: 'chidi@thegoodplace.com',
    roomId: '5',
    checkIn: '2023-10-15',
    checkOut: '2023-10-16',
    status: 'Pending',
    totalAmount: 450,
    paidAmount: 200,
    nights: 1,
  },
  {
    id: 'BK-98991',
    guestName: 'Tahani Al-Jamil',
    guestEmail: 'tahani@thegoodplace.com',
    roomId: '7',
    checkIn: '2023-10-12',
    checkOut: '2023-10-17',
    status: 'Cancelled',
    totalAmount: 3800,
    paidAmount: 0,
    nights: 5,
  },
  {
    id: 'BK-99042',
    guestName: 'Jason Mendoza',
    guestEmail: 'jason@thegoodplace.com',
    roomId: '6',
    checkIn: '2023-10-20',
    checkOut: '2023-10-22',
    status: 'Confirmed',
    totalAmount: 580,
    paidAmount: 580,
    nights: 2,
  },
  {
    id: 'BK-99001',
    guestName: 'Marcus Sterling',
    guestEmail: 'marcus@example.com',
    roomId: '11',
    checkIn: '2023-10-24',
    checkOut: '2023-10-28',
    status: 'Confirmed',
    totalAmount: 1240,
    paidAmount: 1240,
    nights: 4,
  },
  {
    id: 'BK-98115',
    guestName: 'Elena Belova',
    guestEmail: 'elena@example.com',
    roomId: '8',
    checkIn: '2023-10-22',
    checkOut: '2023-10-24',
    status: 'Checked-in',
    totalAmount: 950,
    paidAmount: 950,
    nights: 2,
  },
];

export const transactions: Transaction[] = [
  {
    id: 'TRX-9402',
    bookingId: 'BK-99001',
    guestName: 'James Sterling',
    amount: 1250,
    date: 'Oct 24, 2023',
    method: 'Credit Card',
    status: 'Paid',
  },
  {
    id: 'TRX-9398',
    bookingId: 'BK-99025',
    guestName: 'Marcus Miller',
    amount: 450,
    date: 'Oct 24, 2023',
    method: 'Bank Transfer',
    status: 'Pending',
  },
  {
    id: 'TRX-9385',
    bookingId: 'BK-99042',
    guestName: 'Sarah Chen',
    amount: 2100,
    date: 'Oct 23, 2023',
    method: 'Credit Card',
    status: 'Paid',
  },
  {
    id: 'TRX-9372',
    bookingId: 'BK-98115',
    guestName: 'Lucia Bennett',
    amount: 85,
    date: 'Oct 22, 2023',
    method: 'Cash',
    status: 'Refunded',
  },
];
